apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.K8s_namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.name }}
  replicas: {{ .Values.service.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.name }}
        app.kubernetes.io/name: {{ .Values.service.name }}
        app.kubernetes.io/version: "{{ .Values.service.Release }}"
        app.kubernetes.io/component: service
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/namespace: {{ .Values.service.K8s_namespace }}
    spec:
#      nodeSelector:
#        app: {{ .Values.service.NodeSelector }}
      containers:
      - name: {{ .Values.service.name }}
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        env:
        - name: GITACCOUNT
          value: {{ .Values.service.GITACCOUNT }}
        - name: APITOKEN
          value: {{ .Values.service.APITOKEN }}
        - name: CONFIGFILE
          value: {{ .Values.service.CONFIGFILE }}
        - name: APP
          value: {{ .Values.service.name }}
        - name: RELEASE
          value: "{{ .Values.service.Release }}"
        - name: REPO
          value: {{ .Values.service.GITREPO }}
        - name: APIVER
          value: {{ .Values.service.APIVER }}

        ports:
        - containerPort: {{ .Values.service.containerPort }}

        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.service.externalPort }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.service.externalPort }}

      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
